### PR TITLE
Added TF-IDF

### PR DESCRIPTION
**Pull request by pratik-99**
# Pull Request Description
< replace this line with a brief description of your pull request>

# Sources

Did you include the sources used in creating your contribution? 

- [ ] Yes
- [ ] No

## If you answered No to the last question:

Ensuring the quality of content within Data Science Notes is essential such that the collection is reliable. If you didn't utilize any sources for creating your contribution, could you please list your qualifications or add a link to your LinkedIn profile? 

< replace this line with a brief description of your qualifications or a link to your LinkedIn Profile > 

# Checklist

- [ ] If my pull request is a new page, did I add that page to the `_toc.yml` file?
- [ ] Did I star the repo? ⭐️ (starring helps us attract more viewers and contributors!)
- [ ] Would I like my contribution to be featured on the [@MakeUseofData](https://twitter.com/MakeUseofData) Twitter account? 

## Twitter Username

< Replace this line with your Twitter username if applicable 😊 >

> Thank you for your contribution! We look forward to including it in ***Data Science Notes***

### CODE REVIEW

**Review by wyattowalsh — COMMENTED** [review]
I rearranged some pages and simplified the layout; check out the updated version and let me know if you need any help.

So far things look great, thank you for your contributions 😊

**Review by wyattowalsh — CHANGES_REQUESTED** [review]
Please accept my PR as that will include all necessary changes (I just added content to the section where I added your basics on the index.html within NLP)

**Comment by pratik-99** [comment]
yes everything looks fine @wyattowalsh, Do I need to do something??

**Comment by wyattowalsh** [comment]
I just fixed everything! Sorry about the confusion

**Pull request merged**
