### PR TITLE
Initial update basic.md

### PR DESCRIPTION
**Pull request by pratik-99**
Wrote the basic points that needs to be covered in basic.md file

### CODE REVIEW

**Review by wyattowalsh — CHANGES_REQUESTED** [review]
Hey @pratik-99! Thanks for your pull request! so nice to see some more contributions!

This is great stuff -- almost perfect, just one aspect needs a quick change. 

- This file is currently at the path of `data-science-notes/modeling/basics.md`.
This path would add the content to the modeling basics section. 
I believe that `data-science-notes/modeling/nlp/basics.md` is the correct path for the NLP basics as you have added 😊  - you could just cut and paste everything line 2 and below 
I changed the paths recently to simplify them (removed the chapter numbers) so this may be my fault, I apologize if that's the case!!

**Comment by wyattowalsh** [comment]
@pratik-99 

Also, there was a bug in the pull-request template (fixed now) so unfortunately, you didn't get to see the template (copied at the bottom of this comment). Don't worry about filling it out since this is just an outline right now; I just copied it below so you'd have what the info would have been!

Anyways, we like to feature our contributors and their successful PRs on our Twitter, @MakeUseofData; would you like to be featured, and if so, what is your Twitter username? 😊

---
PR Template: 

# Pull Request Description
< replace this line with a brief description of your pull request>

# Sources

Did you include the sources used in creating your contribution? 

- [ ] Yes
- [ ] No

## If you answered No to the last question:

Ensuring the quality of content within Data Science Notes is essential such that the collection is reliable. If you didn't utilize any sources for creating your contribution, could you please list your qualifications or add a link to your LinkedIn profile? 

< replace this line with a brief description of your qualifications or a link to your LinkedIn Profile > 

# Checklist

- [ ] If my pull request is a new page, did I add that page to the `_toc.yml` file?
- [ ] Did I star the repo? ⭐️ (starring helps us attract more viewers and contributors!)
- [ ] Would I like my contribution to be featured on the [@MakeUseofData](https://twitter.com/MakeUseofData) Twitter account? 

## Twitter Username

< Replace this line with your Twitter username if applicable 😊 >

> Thank you for your contribution! We look forward to including it in ***Data Science Notes***

**Comment by pratik-99** [comment]
Sorry about that but I don't have a twitter handle 😅. I would really be happy if you would connect with me on LinkedIn 😃 
[pratik poojary](https://www.linkedin.com/in/pratik-poojary-8a30421b7/) <-- this is my LinkedIn account.

**Comment by wyattowalsh** [comment]
Oh, no worries then!

And cool, just added ya!

Hopefully, we can work together with some more on ***Data Science Notes*** 😊

**Comment by pratik-99** [comment]
Ya sure @wyattowalsh I will continue to add information's on these topics in basics.md file  😃

**Pull request merged**
