### PR TITLE
Added info to sentence tokenization, Stemming and Lemmatization

### PR DESCRIPTION
**Pull request by pratik-99**
# Pull Request Description
< replace this line with a brief description of your pull request>

# Sources

Did you include the sources used in creating your contribution? 

- [ ] Yes
- [ ] No

## If you answered No to the last question:

Ensuring the quality of content within Data Science Notes is essential such that the collection is reliable. If you didn't utilize any sources for creating your contribution, could you please list your qualifications or add a link to your LinkedIn profile? 

< replace this line with a brief description of your qualifications or a link to your LinkedIn Profile > 

# Checklist

- [ ] If my pull request is a new page, did I add that page to the `_toc.yml` file?
- [ ] Did I star the repo? ⭐️ (starring helps us attract more viewers and contributors!)
- [ ] Would I like my contribution to be featured on the [@MakeUseofData](https://twitter.com/MakeUseofData) Twitter account? 

## Twitter Username

< Replace this line with your Twitter username if applicable 😊 >

> Thank you for your contribution! We look forward to including it in ***Data Science Notes***

### CODE REVIEW

**Comment by pratik-99** [comment]
hey @wyattowalsh I made this pull request but I was facing some difficulty as there was some error while I was trying to push. It said merging is not possible because you have unmerged files, I did git merge --abort after which it worked but I feel some of the info I added to sentence tokenization and stemming have lost their format can you tell me why this is happening

**Comment by wyattowalsh** [comment]
Hey there @pratik-99... That problem might be due to not pulling changes made in the repo before you push. I recommend committing what your work, pulling any changes, then dealing with the merges.

I'll take a look at the PR and fix it!

**Comment by pratik-99** [comment]
hello @wyattowalsh I did pull the changes made in the repo and tried to merge them but I think I didn't commit my changes before making the pull request hence the problem will look into this next time.

**Comment by wyattowalsh** [comment]
Hey @pratik-99!

I was able to fix the merge conflict and successfully merge your PR!

**Comment by pratik-99** [comment]
Thank you @wyattowalsh, can you suggest me what do I need to do so that the changes you made to the remote repository reflect on my local repository I haven't done this before. Can I do this before I make changes in my local repository?

**Pull request merged**
