### PR TITLE
Added info to word tokenizer

### PR DESCRIPTION
**Pull request by pratik-99**
# Pull Request Description
< replace this line with a brief description of your pull request>

# Sources

Did you include the sources used in creating your contribution? 

- [ ] Yes
- [] No

## If you answered No to the last question:

Ensuring the quality of content within Data Science Notes is essential such that the collection is reliable. If you didn't utilize any sources for creating your contribution, could you please list your qualifications or add a link to your LinkedIn profile? 

< replace this line with a brief description of your qualifications or a link to your LinkedIn Profile > 

# Checklist

- [ ] If my pull request is a new page, did I add that page to the `_toc.yml` file?
- [ ] Did I star the repo? ⭐️ (starring helps us attract more viewers and contributors!)
- [ ] Would I like my contribution to be featured on the [@MakeUseofData](https://twitter.com/MakeUseofData) Twitter account? 

## Twitter Username

< Replace this line with your Twitter username if applicable 😊 >

> Thank you for your contribution! We look forward to including it in ***Data Science Notes***

### CODE REVIEW

**Comment by wyattowalsh** [comment]
Fixed the mess up on my end; sorry about the delay!

Thanks again @pratik-99; things look great so far!

**Comment by pratik-99** [comment]
Thank you @wyattowalsh is the content good enough do I need to add something more to word tokenization? Your suggestion would be valuable.

**Comment by wyattowalsh** [comment]
@pratik-99 Allow me to review the subject material a bit more in-depth and I'll get back to you with some possible improvements; hopefully in < 24hrs 😊

**Comment by pratik-99** [comment]
> Perhaps in the meantime, you could look at adding some content in the other sections?

Sure @wyattowalsh I'm looking at adding information to other sections


> Allow me to review the subject material a bit more in-depth and I'll get back to you with some possible improvements; hopefully in < 24hrs 😊

No problem, take your time any feedback at any time would be great😃

**Pull request merged**
